/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessProfile {
  'id' : BusinessProfileId,
  'isApproved' : boolean,
  'contactInfo' : ContactInfo,
  'ownerPrincipal' : Principal,
  'createdAt' : bigint,
  'tier' : BusinessTier,
  'businessName' : string,
  'description' : string,
  'isFeatured' : boolean,
  'address' : string,
  'category' : string,
}
export type BusinessProfileId = bigint;
export type BusinessTier = { 'premium' : null } |
  { 'basic' : null } |
  { 'standard' : null };
export interface ContactInfo {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface Event {
  'id' : EventId,
  'organizer' : string,
  'title' : string,
  'postedAt' : bigint,
  'postedBy' : Principal,
  'contactInfo' : ContactInfo,
  'date' : bigint,
  'time' : bigint,
  'description' : string,
  'isFeatured' : boolean,
  'location' : string,
}
export type EventId = bigint;
export type ExternalBlob = Uint8Array;
export interface Job {
  'id' : JobId,
  'title' : string,
  'postedAt' : bigint,
  'postedBy' : Principal,
  'contactInfo' : ContactInfo,
  'salary' : bigint,
  'description' : string,
  'isActive' : boolean,
  'company' : string,
  'isFeatured' : boolean,
  'location' : string,
}
export type JobId = bigint;
export interface Listing {
  'id' : ListingId,
  'title' : string,
  'postedAt' : bigint,
  'postedBy' : Principal,
  'contactInfo' : ContactInfo,
  'description' : string,
  'isActive' : boolean,
  'isFeatured' : boolean,
  'category' : string,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export type ListingId = bigint;
export interface News {
  'id' : NewsId,
  'title' : string,
  'content' : string,
  'publishedAt' : bigint,
  'author' : string,
  'isFeatured' : boolean,
  'category' : NewsCategory,
  'images' : Array<ExternalBlob>,
}
export type NewsCategory = { 'culture' : null } |
  { 'national' : null } |
  { 'local' : null } |
  { 'sports' : null } |
  { 'politics' : null };
export type NewsId = bigint;
export interface Service {
  'id' : ServiceId,
  'title' : string,
  'postedAt' : bigint,
  'postedBy' : Principal,
  'contactInfo' : ContactInfo,
  'description' : string,
  'isActive' : boolean,
  'priceRange' : string,
  'isFeatured' : boolean,
  'category' : string,
}
export type ServiceId = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveBusiness' : ActorMethod<[BusinessProfileId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBusinessProfile' : ActorMethod<[BusinessProfile], BusinessProfileId>,
  'createEvent' : ActorMethod<[Event], EventId>,
  'createJob' : ActorMethod<[Job], JobId>,
  'createListing' : ActorMethod<[Listing], ListingId>,
  'createNews' : ActorMethod<[News], NewsId>,
  'createService' : ActorMethod<[Service], ServiceId>,
  'deleteBusinessProfile' : ActorMethod<[BusinessProfileId], undefined>,
  'deleteEvent' : ActorMethod<[EventId], undefined>,
  'deleteJob' : ActorMethod<[JobId], undefined>,
  'deleteListing' : ActorMethod<[ListingId], undefined>,
  'deleteNews' : ActorMethod<[NewsId], undefined>,
  'deleteService' : ActorMethod<[ServiceId], undefined>,
  'getAllBusinessProfiles' : ActorMethod<[], Array<BusinessProfile>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getAllNews' : ActorMethod<[], Array<News>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getBusinessProfile' : ActorMethod<
    [BusinessProfileId],
    [] | [BusinessProfile]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[EventId], [] | [Event]>,
  'getFeaturedBusinessProfiles' : ActorMethod<[], Array<BusinessProfile>>,
  'getFeaturedEvents' : ActorMethod<[], Array<Event>>,
  'getFeaturedJobs' : ActorMethod<[], Array<Job>>,
  'getFeaturedListings' : ActorMethod<[], Array<Listing>>,
  'getFeaturedNews' : ActorMethod<[], Array<News>>,
  'getFeaturedServices' : ActorMethod<[], Array<Service>>,
  'getJob' : ActorMethod<[JobId], [] | [Job]>,
  'getListing' : ActorMethod<[ListingId], [] | [Listing]>,
  'getNews' : ActorMethod<[NewsId], [] | [News]>,
  'getPendingBusinessProfiles' : ActorMethod<[], Array<BusinessProfile>>,
  'getService' : ActorMethod<[ServiceId], [] | [Service]>,
  'getStats' : ActorMethod<
    [],
    {
      'listingsCount' : bigint,
      'servicesCount' : bigint,
      'businessesCount' : bigint,
      'newsCount' : bigint,
      'jobsCount' : bigint,
      'eventsCount' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchAll' : ActorMethod<
    [string],
    {
      'businesses' : Array<BusinessProfile>,
      'listings' : Array<Listing>,
      'jobs' : Array<Job>,
      'news' : Array<News>,
      'events' : Array<Event>,
      'services' : Array<Service>,
    }
  >,
  'searchBusinessProfiles' : ActorMethod<[string], Array<BusinessProfile>>,
  'searchEvents' : ActorMethod<[string], Array<Event>>,
  'searchJobs' : ActorMethod<[string], Array<Job>>,
  'searchListings' : ActorMethod<[string], Array<Listing>>,
  'searchNews' : ActorMethod<[string], Array<News>>,
  'searchServices' : ActorMethod<[string], Array<Service>>,
  'toggleBusinessFeatured' : ActorMethod<[BusinessProfileId], undefined>,
  'toggleEventFeatured' : ActorMethod<[EventId], undefined>,
  'toggleJobFeatured' : ActorMethod<[JobId], undefined>,
  'toggleListingFeatured' : ActorMethod<[ListingId], undefined>,
  'toggleNewsFeatured' : ActorMethod<[NewsId], undefined>,
  'toggleServiceFeatured' : ActorMethod<[ServiceId], undefined>,
  'updateBusinessProfile' : ActorMethod<
    [BusinessProfileId, BusinessProfile],
    undefined
  >,
  'updateEvent' : ActorMethod<[EventId, Event], undefined>,
  'updateJob' : ActorMethod<[JobId, Job], undefined>,
  'updateListing' : ActorMethod<[ListingId, Listing], undefined>,
  'updateNews' : ActorMethod<[NewsId, News], undefined>,
  'updateService' : ActorMethod<[ServiceId, Service], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];