/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BusinessProfileId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const BusinessTier = IDL.Variant({
  'premium' : IDL.Null,
  'basic' : IDL.Null,
  'standard' : IDL.Null,
});
export const BusinessProfile = IDL.Record({
  'id' : BusinessProfileId,
  'isApproved' : IDL.Bool,
  'contactInfo' : ContactInfo,
  'ownerPrincipal' : IDL.Principal,
  'createdAt' : IDL.Int,
  'tier' : BusinessTier,
  'businessName' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'address' : IDL.Text,
  'category' : IDL.Text,
});
export const EventId = IDL.Nat;
export const Event = IDL.Record({
  'id' : EventId,
  'organizer' : IDL.Text,
  'title' : IDL.Text,
  'postedAt' : IDL.Int,
  'postedBy' : IDL.Principal,
  'contactInfo' : ContactInfo,
  'date' : IDL.Int,
  'time' : IDL.Int,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'location' : IDL.Text,
});
export const JobId = IDL.Nat;
export const Job = IDL.Record({
  'id' : JobId,
  'title' : IDL.Text,
  'postedAt' : IDL.Int,
  'postedBy' : IDL.Principal,
  'contactInfo' : ContactInfo,
  'salary' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'company' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'location' : IDL.Text,
});
export const ListingId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Listing = IDL.Record({
  'id' : ListingId,
  'title' : IDL.Text,
  'postedAt' : IDL.Int,
  'postedBy' : IDL.Principal,
  'contactInfo' : ContactInfo,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Int,
  'images' : IDL.Vec(ExternalBlob),
});
export const NewsId = IDL.Nat;
export const NewsCategory = IDL.Variant({
  'culture' : IDL.Null,
  'national' : IDL.Null,
  'local' : IDL.Null,
  'sports' : IDL.Null,
  'politics' : IDL.Null,
});
export const News = IDL.Record({
  'id' : NewsId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedAt' : IDL.Int,
  'author' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : NewsCategory,
  'images' : IDL.Vec(ExternalBlob),
});
export const ServiceId = IDL.Nat;
export const Service = IDL.Record({
  'id' : ServiceId,
  'title' : IDL.Text,
  'postedAt' : IDL.Int,
  'postedBy' : IDL.Principal,
  'contactInfo' : ContactInfo,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'priceRange' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveBusiness' : IDL.Func([BusinessProfileId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBusinessProfile' : IDL.Func(
      [BusinessProfile],
      [BusinessProfileId],
      [],
    ),
  'createEvent' : IDL.Func([Event], [EventId], []),
  'createJob' : IDL.Func([Job], [JobId], []),
  'createListing' : IDL.Func([Listing], [ListingId], []),
  'createNews' : IDL.Func([News], [NewsId], []),
  'createService' : IDL.Func([Service], [ServiceId], []),
  'deleteBusinessProfile' : IDL.Func([BusinessProfileId], [], []),
  'deleteEvent' : IDL.Func([EventId], [], []),
  'deleteJob' : IDL.Func([JobId], [], []),
  'deleteListing' : IDL.Func([ListingId], [], []),
  'deleteNews' : IDL.Func([NewsId], [], []),
  'deleteService' : IDL.Func([ServiceId], [], []),
  'getAllBusinessProfiles' : IDL.Func(
      [],
      [IDL.Vec(BusinessProfile)],
      ['query'],
    ),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getBusinessProfile' : IDL.Func(
      [BusinessProfileId],
      [IDL.Opt(BusinessProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([EventId], [IDL.Opt(Event)], ['query']),
  'getFeaturedBusinessProfiles' : IDL.Func(
      [],
      [IDL.Vec(BusinessProfile)],
      ['query'],
    ),
  'getFeaturedEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getFeaturedJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getFeaturedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getFeaturedNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
  'getFeaturedServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
  'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
  'getNews' : IDL.Func([NewsId], [IDL.Opt(News)], ['query']),
  'getPendingBusinessProfiles' : IDL.Func(
      [],
      [IDL.Vec(BusinessProfile)],
      ['query'],
    ),
  'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'listingsCount' : IDL.Nat,
          'servicesCount' : IDL.Nat,
          'businessesCount' : IDL.Nat,
          'newsCount' : IDL.Nat,
          'jobsCount' : IDL.Nat,
          'eventsCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchAll' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'businesses' : IDL.Vec(BusinessProfile),
          'listings' : IDL.Vec(Listing),
          'jobs' : IDL.Vec(Job),
          'news' : IDL.Vec(News),
          'events' : IDL.Vec(Event),
          'services' : IDL.Vec(Service),
        }),
      ],
      ['query'],
    ),
  'searchBusinessProfiles' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BusinessProfile)],
      ['query'],
    ),
  'searchEvents' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'searchJobs' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
  'searchListings' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
  'searchNews' : IDL.Func([IDL.Text], [IDL.Vec(News)], ['query']),
  'searchServices' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
  'toggleBusinessFeatured' : IDL.Func([BusinessProfileId], [], []),
  'toggleEventFeatured' : IDL.Func([EventId], [], []),
  'toggleJobFeatured' : IDL.Func([JobId], [], []),
  'toggleListingFeatured' : IDL.Func([ListingId], [], []),
  'toggleNewsFeatured' : IDL.Func([NewsId], [], []),
  'toggleServiceFeatured' : IDL.Func([ServiceId], [], []),
  'updateBusinessProfile' : IDL.Func(
      [BusinessProfileId, BusinessProfile],
      [],
      [],
    ),
  'updateEvent' : IDL.Func([EventId, Event], [], []),
  'updateJob' : IDL.Func([JobId, Job], [], []),
  'updateListing' : IDL.Func([ListingId, Listing], [], []),
  'updateNews' : IDL.Func([NewsId, News], [], []),
  'updateService' : IDL.Func([ServiceId, Service], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BusinessProfileId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const BusinessTier = IDL.Variant({
    'premium' : IDL.Null,
    'basic' : IDL.Null,
    'standard' : IDL.Null,
  });
  const BusinessProfile = IDL.Record({
    'id' : BusinessProfileId,
    'isApproved' : IDL.Bool,
    'contactInfo' : ContactInfo,
    'ownerPrincipal' : IDL.Principal,
    'createdAt' : IDL.Int,
    'tier' : BusinessTier,
    'businessName' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'address' : IDL.Text,
    'category' : IDL.Text,
  });
  const EventId = IDL.Nat;
  const Event = IDL.Record({
    'id' : EventId,
    'organizer' : IDL.Text,
    'title' : IDL.Text,
    'postedAt' : IDL.Int,
    'postedBy' : IDL.Principal,
    'contactInfo' : ContactInfo,
    'date' : IDL.Int,
    'time' : IDL.Int,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'location' : IDL.Text,
  });
  const JobId = IDL.Nat;
  const Job = IDL.Record({
    'id' : JobId,
    'title' : IDL.Text,
    'postedAt' : IDL.Int,
    'postedBy' : IDL.Principal,
    'contactInfo' : ContactInfo,
    'salary' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'company' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'location' : IDL.Text,
  });
  const ListingId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Listing = IDL.Record({
    'id' : ListingId,
    'title' : IDL.Text,
    'postedAt' : IDL.Int,
    'postedBy' : IDL.Principal,
    'contactInfo' : ContactInfo,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Int,
    'images' : IDL.Vec(ExternalBlob),
  });
  const NewsId = IDL.Nat;
  const NewsCategory = IDL.Variant({
    'culture' : IDL.Null,
    'national' : IDL.Null,
    'local' : IDL.Null,
    'sports' : IDL.Null,
    'politics' : IDL.Null,
  });
  const News = IDL.Record({
    'id' : NewsId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedAt' : IDL.Int,
    'author' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : NewsCategory,
    'images' : IDL.Vec(ExternalBlob),
  });
  const ServiceId = IDL.Nat;
  const Service = IDL.Record({
    'id' : ServiceId,
    'title' : IDL.Text,
    'postedAt' : IDL.Int,
    'postedBy' : IDL.Principal,
    'contactInfo' : ContactInfo,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'priceRange' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveBusiness' : IDL.Func([BusinessProfileId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBusinessProfile' : IDL.Func(
        [BusinessProfile],
        [BusinessProfileId],
        [],
      ),
    'createEvent' : IDL.Func([Event], [EventId], []),
    'createJob' : IDL.Func([Job], [JobId], []),
    'createListing' : IDL.Func([Listing], [ListingId], []),
    'createNews' : IDL.Func([News], [NewsId], []),
    'createService' : IDL.Func([Service], [ServiceId], []),
    'deleteBusinessProfile' : IDL.Func([BusinessProfileId], [], []),
    'deleteEvent' : IDL.Func([EventId], [], []),
    'deleteJob' : IDL.Func([JobId], [], []),
    'deleteListing' : IDL.Func([ListingId], [], []),
    'deleteNews' : IDL.Func([NewsId], [], []),
    'deleteService' : IDL.Func([ServiceId], [], []),
    'getAllBusinessProfiles' : IDL.Func(
        [],
        [IDL.Vec(BusinessProfile)],
        ['query'],
      ),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getBusinessProfile' : IDL.Func(
        [BusinessProfileId],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([EventId], [IDL.Opt(Event)], ['query']),
    'getFeaturedBusinessProfiles' : IDL.Func(
        [],
        [IDL.Vec(BusinessProfile)],
        ['query'],
      ),
    'getFeaturedEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getFeaturedJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getFeaturedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getFeaturedNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
    'getFeaturedServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
    'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
    'getNews' : IDL.Func([NewsId], [IDL.Opt(News)], ['query']),
    'getPendingBusinessProfiles' : IDL.Func(
        [],
        [IDL.Vec(BusinessProfile)],
        ['query'],
      ),
    'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'listingsCount' : IDL.Nat,
            'servicesCount' : IDL.Nat,
            'businessesCount' : IDL.Nat,
            'newsCount' : IDL.Nat,
            'jobsCount' : IDL.Nat,
            'eventsCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchAll' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'businesses' : IDL.Vec(BusinessProfile),
            'listings' : IDL.Vec(Listing),
            'jobs' : IDL.Vec(Job),
            'news' : IDL.Vec(News),
            'events' : IDL.Vec(Event),
            'services' : IDL.Vec(Service),
          }),
        ],
        ['query'],
      ),
    'searchBusinessProfiles' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BusinessProfile)],
        ['query'],
      ),
    'searchEvents' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'searchJobs' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
    'searchListings' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
    'searchNews' : IDL.Func([IDL.Text], [IDL.Vec(News)], ['query']),
    'searchServices' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
    'toggleBusinessFeatured' : IDL.Func([BusinessProfileId], [], []),
    'toggleEventFeatured' : IDL.Func([EventId], [], []),
    'toggleJobFeatured' : IDL.Func([JobId], [], []),
    'toggleListingFeatured' : IDL.Func([ListingId], [], []),
    'toggleNewsFeatured' : IDL.Func([NewsId], [], []),
    'toggleServiceFeatured' : IDL.Func([ServiceId], [], []),
    'updateBusinessProfile' : IDL.Func(
        [BusinessProfileId, BusinessProfile],
        [],
        [],
      ),
    'updateEvent' : IDL.Func([EventId, Event], [], []),
    'updateJob' : IDL.Func([JobId, Job], [], []),
    'updateListing' : IDL.Func([ListingId, Listing], [], []),
    'updateNews' : IDL.Func([NewsId, News], [], []),
    'updateService' : IDL.Func([ServiceId, Service], [], []),
  });
};

export const init = ({ IDL }) => { return []; };