/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ServiceId = bigint;
export interface BusinessProfile {
    id: BusinessProfileId;
    isApproved: boolean;
    contactInfo: ContactInfo;
    ownerPrincipal: Principal;
    createdAt: bigint;
    tier: BusinessTier;
    businessName: string;
    description: string;
    isFeatured: boolean;
    address: string;
    category: string;
}
export type NewsId = bigint;
export interface Listing {
    id: ListingId;
    title: string;
    postedAt: bigint;
    postedBy: Principal;
    contactInfo: ContactInfo;
    description: string;
    isActive: boolean;
    isFeatured: boolean;
    category: string;
    price: bigint;
    images: Array<ExternalBlob>;
}
export type EventId = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Service {
    id: ServiceId;
    title: string;
    postedAt: bigint;
    postedBy: Principal;
    contactInfo: ContactInfo;
    description: string;
    isActive: boolean;
    priceRange: string;
    isFeatured: boolean;
    category: string;
}
export type JobId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Event {
    id: EventId;
    organizer: string;
    title: string;
    postedAt: bigint;
    postedBy: Principal;
    contactInfo: ContactInfo;
    date: bigint;
    time: bigint;
    description: string;
    isFeatured: boolean;
    location: string;
}
export interface Job {
    id: JobId;
    title: string;
    postedAt: bigint;
    postedBy: Principal;
    contactInfo: ContactInfo;
    salary: bigint;
    description: string;
    isActive: boolean;
    company: string;
    isFeatured: boolean;
    location: string;
}
export type ListingId = bigint;
export interface News {
    id: NewsId;
    title: string;
    content: string;
    publishedAt: bigint;
    author: string;
    isFeatured: boolean;
    category: NewsCategory;
    images: Array<ExternalBlob>;
}
export type BusinessProfileId = bigint;
export interface ContactInfo {
    name: string;
    email: string;
    phone: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BusinessTier {
    premium = "premium",
    basic = "basic",
    standard = "standard"
}
export enum NewsCategory {
    culture = "culture",
    national = "national",
    local = "local",
    sports = "sports",
    politics = "politics"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveBusiness(businessId: BusinessProfileId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBusinessProfile(profile: BusinessProfile): Promise<BusinessProfileId>;
    createEvent(event: Event): Promise<EventId>;
    createJob(job: Job): Promise<JobId>;
    createListing(listing: Listing): Promise<ListingId>;
    createNews(news: News): Promise<NewsId>;
    createService(service: Service): Promise<ServiceId>;
    deleteBusinessProfile(businessId: BusinessProfileId): Promise<void>;
    deleteEvent(eventId: EventId): Promise<void>;
    deleteJob(jobId: JobId): Promise<void>;
    deleteListing(listingId: ListingId): Promise<void>;
    deleteNews(newsId: NewsId): Promise<void>;
    deleteService(serviceId: ServiceId): Promise<void>;
    getAllBusinessProfiles(): Promise<Array<BusinessProfile>>;
    getAllEvents(): Promise<Array<Event>>;
    getAllJobs(): Promise<Array<Job>>;
    getAllListings(): Promise<Array<Listing>>;
    getAllNews(): Promise<Array<News>>;
    getAllServices(): Promise<Array<Service>>;
    getBusinessProfile(businessId: BusinessProfileId): Promise<BusinessProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEvent(eventId: EventId): Promise<Event | null>;
    getFeaturedBusinessProfiles(): Promise<Array<BusinessProfile>>;
    getFeaturedEvents(): Promise<Array<Event>>;
    getFeaturedJobs(): Promise<Array<Job>>;
    getFeaturedListings(): Promise<Array<Listing>>;
    getFeaturedNews(): Promise<Array<News>>;
    getFeaturedServices(): Promise<Array<Service>>;
    getJob(jobId: JobId): Promise<Job | null>;
    getListing(listingId: ListingId): Promise<Listing | null>;
    getNews(newsId: NewsId): Promise<News | null>;
    getPendingBusinessProfiles(): Promise<Array<BusinessProfile>>;
    getService(serviceId: ServiceId): Promise<Service | null>;
    getStats(): Promise<{
        listingsCount: bigint;
        servicesCount: bigint;
        businessesCount: bigint;
        newsCount: bigint;
        jobsCount: bigint;
        eventsCount: bigint;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchAll(keyword: string): Promise<{
        businesses: Array<BusinessProfile>;
        listings: Array<Listing>;
        jobs: Array<Job>;
        news: Array<News>;
        events: Array<Event>;
        services: Array<Service>;
    }>;
    searchBusinessProfiles(keyword: string): Promise<Array<BusinessProfile>>;
    searchEvents(keyword: string): Promise<Array<Event>>;
    searchJobs(keyword: string): Promise<Array<Job>>;
    searchListings(keyword: string): Promise<Array<Listing>>;
    searchNews(keyword: string): Promise<Array<News>>;
    searchServices(keyword: string): Promise<Array<Service>>;
    toggleBusinessFeatured(businessId: BusinessProfileId): Promise<void>;
    toggleEventFeatured(eventId: EventId): Promise<void>;
    toggleJobFeatured(jobId: JobId): Promise<void>;
    toggleListingFeatured(listingId: ListingId): Promise<void>;
    toggleNewsFeatured(newsId: NewsId): Promise<void>;
    toggleServiceFeatured(serviceId: ServiceId): Promise<void>;
    updateBusinessProfile(businessId: BusinessProfileId, profile: BusinessProfile): Promise<void>;
    updateEvent(eventId: EventId, event: Event): Promise<void>;
    updateJob(jobId: JobId, job: Job): Promise<void>;
    updateListing(listingId: ListingId, listing: Listing): Promise<void>;
    updateNews(newsId: NewsId, news: News): Promise<void>;
    updateService(serviceId: ServiceId, service: Service): Promise<void>;
}
import type { BusinessProfile as _BusinessProfile, BusinessProfileId as _BusinessProfileId, BusinessTier as _BusinessTier, ContactInfo as _ContactInfo, Event as _Event, ExternalBlob as _ExternalBlob, Job as _Job, Listing as _Listing, ListingId as _ListingId, News as _News, NewsCategory as _NewsCategory, NewsId as _NewsId, Service as _Service, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveBusiness(arg0: BusinessProfileId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveBusiness(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveBusiness(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBusinessProfile(arg0: BusinessProfile): Promise<BusinessProfileId> {
        if (this.processError) {
            try {
                const result = await this.actor.createBusinessProfile(to_candid_BusinessProfile_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBusinessProfile(to_candid_BusinessProfile_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEvent(arg0: Event): Promise<EventId> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0);
            return result;
        }
    }
    async createJob(arg0: Job): Promise<JobId> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(arg0);
            return result;
        }
    }
    async createListing(arg0: Listing): Promise<ListingId> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(await to_candid_Listing_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(await to_candid_Listing_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createNews(arg0: News): Promise<NewsId> {
        if (this.processError) {
            try {
                const result = await this.actor.createNews(await to_candid_News_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNews(await to_candid_News_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createService(arg0: Service): Promise<ServiceId> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(arg0);
            return result;
        }
    }
    async deleteBusinessProfile(arg0: BusinessProfileId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBusinessProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBusinessProfile(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: EventId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteJob(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async deleteListing(arg0: ListingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async deleteNews(arg0: NewsId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNews(arg0);
            return result;
        }
    }
    async deleteService(arg0: ServiceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async getAllBusinessProfiles(): Promise<Array<BusinessProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBusinessProfiles();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBusinessProfiles();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return result;
        }
    }
    async getAllJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return result;
        }
    }
    async getAllListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNews(): Promise<Array<News>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNews();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNews();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return result;
        }
    }
    async getBusinessProfile(arg0: BusinessProfileId): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: EventId): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedBusinessProfiles(): Promise<Array<BusinessProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedBusinessProfiles();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedBusinessProfiles();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedEvents();
            return result;
        }
    }
    async getFeaturedJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedJobs();
            return result;
        }
    }
    async getFeaturedListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedListings();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedListings();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedNews(): Promise<Array<News>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedNews();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedNews();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedServices();
            return result;
        }
    }
    async getJob(arg0: JobId): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: ListingId): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNews(arg0: NewsId): Promise<News | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNews(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNews(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingBusinessProfiles(): Promise<Array<BusinessProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingBusinessProfiles();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingBusinessProfiles();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: ServiceId): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<{
        listingsCount: bigint;
        servicesCount: bigint;
        businessesCount: bigint;
        newsCount: bigint;
        jobsCount: bigint;
        eventsCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchAll(arg0: string): Promise<{
        businesses: Array<BusinessProfile>;
        listings: Array<Listing>;
        jobs: Array<Job>;
        news: Array<News>;
        events: Array<Event>;
        services: Array<Service>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAll(arg0);
                return from_candid_record_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAll(arg0);
            return from_candid_record_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchBusinessProfiles(arg0: string): Promise<Array<BusinessProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchBusinessProfiles(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchBusinessProfiles(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchEvents(arg0: string): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchEvents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchEvents(arg0);
            return result;
        }
    }
    async searchJobs(arg0: string): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJobs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJobs(arg0);
            return result;
        }
    }
    async searchListings(arg0: string): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListings(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListings(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchNews(arg0: string): Promise<Array<News>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchNews(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchNews(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchServices(arg0: string): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchServices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchServices(arg0);
            return result;
        }
    }
    async toggleBusinessFeatured(arg0: BusinessProfileId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleBusinessFeatured(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleBusinessFeatured(arg0);
            return result;
        }
    }
    async toggleEventFeatured(arg0: EventId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleEventFeatured(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleEventFeatured(arg0);
            return result;
        }
    }
    async toggleJobFeatured(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleJobFeatured(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleJobFeatured(arg0);
            return result;
        }
    }
    async toggleListingFeatured(arg0: ListingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleListingFeatured(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleListingFeatured(arg0);
            return result;
        }
    }
    async toggleNewsFeatured(arg0: NewsId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleNewsFeatured(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleNewsFeatured(arg0);
            return result;
        }
    }
    async toggleServiceFeatured(arg0: ServiceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleServiceFeatured(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleServiceFeatured(arg0);
            return result;
        }
    }
    async updateBusinessProfile(arg0: BusinessProfileId, arg1: BusinessProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBusinessProfile(arg0, to_candid_BusinessProfile_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBusinessProfile(arg0, to_candid_BusinessProfile_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEvent(arg0: EventId, arg1: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1);
            return result;
        }
    }
    async updateJob(arg0: JobId, arg1: Job): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, arg1);
            return result;
        }
    }
    async updateListing(arg0: ListingId, arg1: Listing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, await to_candid_Listing_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, await to_candid_Listing_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateNews(arg0: NewsId, arg1: News): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNews(arg0, await to_candid_News_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNews(arg0, await to_candid_News_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateService(arg0: ServiceId, arg1: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BusinessProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessProfile): BusinessProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_BusinessTier_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessTier): BusinessTier {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Listing_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Promise<Listing> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_NewsCategory_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsCategory): NewsCategory {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_News_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _News): Promise<News> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusinessProfile]): BusinessProfile | null {
    return value.length === 0 ? null : from_candid_BusinessProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Event | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Promise<Listing | null> {
    return value.length === 0 ? null : await from_candid_Listing_n28(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_News]): Promise<News | null> {
    return value.length === 0 ? null : await from_candid_News_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BusinessProfileId;
    isApproved: boolean;
    contactInfo: _ContactInfo;
    ownerPrincipal: Principal;
    createdAt: bigint;
    tier: _BusinessTier;
    businessName: string;
    description: string;
    isFeatured: boolean;
    address: string;
    category: string;
}): {
    id: BusinessProfileId;
    isApproved: boolean;
    contactInfo: ContactInfo;
    ownerPrincipal: Principal;
    createdAt: bigint;
    tier: BusinessTier;
    businessName: string;
    description: string;
    isFeatured: boolean;
    address: string;
    category: string;
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        contactInfo: value.contactInfo,
        ownerPrincipal: value.ownerPrincipal,
        createdAt: value.createdAt,
        tier: from_candid_BusinessTier_n25(_uploadFile, _downloadFile, value.tier),
        businessName: value.businessName,
        description: value.description,
        isFeatured: value.isFeatured,
        address: value.address,
        category: value.category
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ListingId;
    title: string;
    postedAt: bigint;
    postedBy: Principal;
    contactInfo: _ContactInfo;
    description: string;
    isActive: boolean;
    isFeatured: boolean;
    category: string;
    price: bigint;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: ListingId;
    title: string;
    postedAt: bigint;
    postedBy: Principal;
    contactInfo: ContactInfo;
    description: string;
    isActive: boolean;
    isFeatured: boolean;
    category: string;
    price: bigint;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        postedAt: value.postedAt,
        postedBy: value.postedBy,
        contactInfo: value.contactInfo,
        description: value.description,
        isActive: value.isActive,
        isFeatured: value.isFeatured,
        category: value.category,
        price: value.price,
        images: await from_candid_vec_n30(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NewsId;
    title: string;
    content: string;
    publishedAt: bigint;
    author: string;
    isFeatured: boolean;
    category: _NewsCategory;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: NewsId;
    title: string;
    content: string;
    publishedAt: bigint;
    author: string;
    isFeatured: boolean;
    category: NewsCategory;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        publishedAt: value.publishedAt,
        author: value.author,
        isFeatured: value.isFeatured,
        category: from_candid_NewsCategory_n35(_uploadFile, _downloadFile, value.category),
        images: await from_candid_vec_n30(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businesses: Array<_BusinessProfile>;
    listings: Array<_Listing>;
    jobs: Array<_Job>;
    news: Array<_News>;
    events: Array<_Event>;
    services: Array<_Service>;
}): Promise<{
    businesses: Array<BusinessProfile>;
    listings: Array<Listing>;
    jobs: Array<Job>;
    news: Array<News>;
    events: Array<Event>;
    services: Array<Service>;
}> {
    return {
        businesses: from_candid_vec_n22(_uploadFile, _downloadFile, value.businesses),
        listings: await from_candid_vec_n27(_uploadFile, _downloadFile, value.listings),
        jobs: value.jobs,
        news: await from_candid_vec_n32(_uploadFile, _downloadFile, value.news),
        events: value.events,
        services: value.services
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    basic: null;
} | {
    standard: null;
}): BusinessTier {
    return "premium" in value ? BusinessTier.premium : "basic" in value ? BusinessTier.basic : "standard" in value ? BusinessTier.standard : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    culture: null;
} | {
    national: null;
} | {
    local: null;
} | {
    sports: null;
} | {
    politics: null;
}): NewsCategory {
    return "culture" in value ? NewsCategory.culture : "national" in value ? NewsCategory.national : "local" in value ? NewsCategory.local : "sports" in value ? NewsCategory.sports : "politics" in value ? NewsCategory.politics : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BusinessProfile>): Array<BusinessProfile> {
    return value.map((x)=>from_candid_BusinessProfile_n23(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Promise<Array<Listing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Listing_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_News>): Promise<Array<News>> {
    return await Promise.all(value.map(async (x)=>await from_candid_News_n33(_uploadFile, _downloadFile, x)));
}
function to_candid_BusinessProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessProfile): _BusinessProfile {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_BusinessTier_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessTier): _BusinessTier {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Listing_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Listing): Promise<_Listing> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_NewsCategory_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsCategory): _NewsCategory {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function to_candid_News_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: News): Promise<_News> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: BusinessProfileId;
    isApproved: boolean;
    contactInfo: ContactInfo;
    ownerPrincipal: Principal;
    createdAt: bigint;
    tier: BusinessTier;
    businessName: string;
    description: string;
    isFeatured: boolean;
    address: string;
    category: string;
}): {
    id: _BusinessProfileId;
    isApproved: boolean;
    contactInfo: _ContactInfo;
    ownerPrincipal: Principal;
    createdAt: bigint;
    tier: _BusinessTier;
    businessName: string;
    description: string;
    isFeatured: boolean;
    address: string;
    category: string;
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        contactInfo: value.contactInfo,
        ownerPrincipal: value.ownerPrincipal,
        createdAt: value.createdAt,
        tier: to_candid_BusinessTier_n12(_uploadFile, _downloadFile, value.tier),
        businessName: value.businessName,
        description: value.description,
        isFeatured: value.isFeatured,
        address: value.address,
        category: value.category
    };
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ListingId;
    title: string;
    postedAt: bigint;
    postedBy: Principal;
    contactInfo: ContactInfo;
    description: string;
    isActive: boolean;
    isFeatured: boolean;
    category: string;
    price: bigint;
    images: Array<ExternalBlob>;
}): Promise<{
    id: _ListingId;
    title: string;
    postedAt: bigint;
    postedBy: Principal;
    contactInfo: _ContactInfo;
    description: string;
    isActive: boolean;
    isFeatured: boolean;
    category: string;
    price: bigint;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        postedAt: value.postedAt,
        postedBy: value.postedBy,
        contactInfo: value.contactInfo,
        description: value.description,
        isActive: value.isActive,
        isFeatured: value.isFeatured,
        category: value.category,
        price: value.price,
        images: await to_candid_vec_n16(_uploadFile, _downloadFile, value.images)
    };
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: NewsId;
    title: string;
    content: string;
    publishedAt: bigint;
    author: string;
    isFeatured: boolean;
    category: NewsCategory;
    images: Array<ExternalBlob>;
}): Promise<{
    id: _NewsId;
    title: string;
    content: string;
    publishedAt: bigint;
    author: string;
    isFeatured: boolean;
    category: _NewsCategory;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        publishedAt: value.publishedAt,
        author: value.author,
        isFeatured: value.isFeatured,
        category: to_candid_NewsCategory_n20(_uploadFile, _downloadFile, value.category),
        images: await to_candid_vec_n16(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessTier): {
    premium: null;
} | {
    basic: null;
} | {
    standard: null;
} {
    return value == BusinessTier.premium ? {
        premium: null
    } : value == BusinessTier.basic ? {
        basic: null
    } : value == BusinessTier.standard ? {
        standard: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsCategory): {
    culture: null;
} | {
    national: null;
} | {
    local: null;
} | {
    sports: null;
} | {
    politics: null;
} {
    return value == NewsCategory.culture ? {
        culture: null
    } : value == NewsCategory.national ? {
        national: null
    } : value == NewsCategory.local ? {
        local: null
    } : value == NewsCategory.sports ? {
        sports: null
    } : value == NewsCategory.politics ? {
        politics: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
